site_name: 海蓝大陆文档
site_description: 'B站up主尘甲出资并设计的RPG类Minecraft服务器“海蓝大陆”使用文档'
site_url: https://docs.chenjia.one/
nav:
    - 欢迎: index.md
    - 开始游戏:
      - 如何进服？: start_game/howtojoin.md
      - 常见问题: start_game/faq.md
      - 注意事项: start_game/rule.md
    - 插件:
      - CMI: plugin/cmi.md
      - 地皮: plugin/plotsquared.md
      - 菜单: plugin/menu.md
      - 统计: plugin/plan.md
    - 物品:
      - 消耗品: item/Consumables.md 
      - 装备: item/equipment.md
      - 树木: item/trees.md
      - 矿石: item/ore.md
      - 食物: item/food.md
      - 材料: item/materials.md
      - 工具: item/tools.md
    - 贡献者: contributor.md
    - 关于: about.md
theme:
  name: material
  favicon: img/favicon.png
  logo: img/logo.webp
  locale: zh
  features:
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.top
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - css/extra.css

extra:
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/12325142
    - icon: fontawesome/brands/qq
      link: https://jq.qq.com/?_wv=1027&k=vXkTtV8K

copyright: Copyright &copy; 页面内容均以<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh" target="_blank" rel="nofollow noreferrer">CC BY-NC-SA 4.0</a>条款授权
