name: Build site and publish

on:
    workflow_dispatch:
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build Public
        permissions:
            contents: read
            deployments: write
        steps:
            - name: Install nix
              uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31

            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

            - name: Build site
              run: |
                  nix build .#chenjia-docs --print-out-paths | tee store_path
                  echo "store_path=$(<store_path)" >> "$GITHUB_ENV"
                  find . -mindepth 1 -delete

            - name: Publish to Cloudflare Pages
              uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  command: pages deploy ${{ env.store_path }} --project-name=chenjia-docs
